---
- name: Gather logs files from remote systems
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Find logs
      find:
        paths: /var/log/
        patterns: 'secure*,auth.log*'
        recurse: yes
      register: _logs

    - name: Fetch logs
      fetch:
        src: "{{ item.path }}"
        dest: logs
      with_items:
        - "{{ _logs.files }}"
