---
- name: Gather logs files from test remote systems
  hosts: panda
  become: yes

  tasks:
    - name: Find logs
      find:
        paths: /var/log/
        patterns: 'secure*'
        recurse: yes
      register: _logs

    - name: Fetch logs
      fetch:
        src: "{{ item.path }}"
        dest: logs
with_items: "{{ _logs.files }}"
